# Site settings
title: JorgeGarro
email: inbox@jorgegarro.com
description: >- # this means to ignore newlines until "baseurl:"
  IT, Arts & Life
baseurl: ""
url: "https://jgarro2.github.io"
show_excerpts: true
rss: RSS Feed
twitter_username: garrett087
github_username:  jgarro2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: "/:title/"